### ISSUE TITLE
如何在linux上debug和下载

### ISSUE THREAD

**Issue by ccldmf** [yanmowudi/diy-swm341#1]
你好，请问你知道如何在ubuntu上使用JLink debug吗？我clone你的repo， 并且在demo_uart_printf中build，build成功。我开启GDB server， 然后target remote :ip 连接时，可以连接到板子。然后load out/swm341.elf 0x00000000 或者0x20000000,然后运行，但是跑不到main()那里，我的板子是swm34svet6。请问你有在linux上debug过吗？还需要修改什么吗？以及如何下载bin到板子。谢谢！

**Comment by LikWoody** [comment]
> 你好，请问你知道如何在ubuntu上使用JLink debug吗？我clone你的repo， 并且在demo_uart_printf中build，build成功。我开启GDB server， 然后target remote :ip 连接时，可以连接到板子。然后load out/swm341.elf 0x00000000 或者0x20000000,然后运行，但是跑不到main()那里，我的板子是swm34svet6。请问你有在linux上debug过吗？还需要修改什么吗？以及如何下载bin到板子。谢谢！

我只是在WSL下进行了编译，下载是在WINDOWS下用JFLASH操作的。你可以参考一下STM32在linux下是如何debug的，应该都是一样的。

**Comment by ccldmf** [comment]
OK，感谢。我可以在linux上debug STM32，但是Synwit的MCU还是第一次弄，有点不太熟悉，我再看看。

**Comment by ccldmf** [comment]
> > 你好，请问你知道如何在ubuntu上使用JLink debug吗？我clone你的repo， 并且在demo_uart_printf中build，build成功。我开启GDB server， 然后target remote :ip 连接时，可以连接到板子。然后load out/swm341.elf 0x00000000 或者0x20000000,然后运行，但是跑不到main()那里，我的板子是swm34svet6。请问你有在linux上debug过吗？还需要修改什么吗？以及如何下载bin到板子。谢谢！
> 
> 我只是在WSL下进行了编译，下载是在WINDOWS下用JFLASH操作的。你可以参考一下STM32在linux下是如何debug的，应该都是一样的。

OK，感谢。我可以在linux上debug STM32，但是Synwit的MCU还是第一次弄，有点不太熟悉，我再看看。
